exclude: ['README.md', 'Rakefile', 'Gemfile', 'Gemfile.lock']
lsi: false
name: pld
markdown: redcarpet
paginate: 5
pygments: true
safe: true

css:
  - /css/custom.css
  - /css/style.css
  - /css/syntax.css
